### ISSUE TITLE
Post-Publishing Tests Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microshed-testing#3]
Post-Publishing Tests
- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [x] Clone repo and test finish directory with no error

Other post-publishing tasks (to be done by the Admin Team)
- [x] Add description for the repo with link to guide's published website
- [x] Double check the SEO title and description are added for the guide
- [x] Create the Home and Branches wiki pages
- [x] Ensure automated test for PR and Continuous Tests are enabled for both `master` and `qa` branches and are run on Travis, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
- [x] Ensure the automated tests are running successfully for the daily builds
- [x] Ensure the automated tests are running successfully for the daily docker image, if the guide uses a docker image
- [x] Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#subscribing-static-guides-repositories-to-a-slack-channel)
- [x] Enable `master` and `qa` branches lock down, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
    -  make sure the Branch protection rules were created
- [x] Add the new guide's repo to the `OpenLiberty/guides-common` ZenHub board
- [x] Delete `dev` branch
- [ ] (Optional) Send announcement to slack channel(s)
- [ ] Arrange a demo at the EOI meeting

**Comment by NimG98** [comment]
On Linux and Mac, the url http://localhost:9080/guide-microshed-testing doesn't work but http://localhost:9080/guide-microshed-testing/people works.

**Comment by gkwan-ibm** [comment]
@NimG98 "the url  http://localhost:9080/guide-microshed-testing" is just the context root, i.e. not an api. It should better be a plain text instead of a link.

**Comment by NimG98** [comment]
Changed url from link to text in PR: https://github.com/OpenLiberty/guide-microshed-testing/pull/6
